package com.da.da_25_26.products;

import java.math.BigDecimal;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.NamedQuery;

/**
 * A catalog item available for purchase in the system. This entitiy serves as
 * the primary data model for product management.
 */
@Entity
@NamedQuery(name = "Product.fetchAllBlue", query = "SELECT p FROM Product p WHERE p.color = 'Blue'")
@NamedQuery(name = "Product.fetchAllBlack", query = "SELECT p FROM  Product p WHERE p.color = 'Black'")
@NamedQuery(name = "Product.fetchAllBrown", query = "SELECT p FROM Product p WHERE p.color = 'Brown'")
@NamedQuery(name = "Product.fetchAllGray", query = "SELECT p FROM Product p WHERE p.color = 'Gray'")
public class Product {

  /*
   * The unique id for the product. Gets automatically generated by
   * the @GeneratedValue
   */
  @Id
  @GeneratedValue
  private long id;
  /*
   * The display name for the product
   */
  private String name;
  /*
   * The unit price for the product
   */
  private BigDecimal price;
  /*
   * The physical size for the product
   */
  private String size;
  /*
   * The dominant color for the product
   */
  private String color;

  Product(String name, BigDecimal price, String size, String color) {
    this.name = name;
    this.price = price;
    this.size = size;
    this.color = color;
  }

  public Product() {

  }

  // Getters and Setters for the private attributes
  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public String getSize() {
    return size;
  }

  public void setSize(String size) {
    this.size = size;
  }

  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }
}
